// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/profile_service/profile.proto

#include "services/profile_service/profile.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace profile {

inline constexpr ProfileRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        nickname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        photo_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        quote_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        bio_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProfileRequest::ProfileRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ProfileRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProfileRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProfileRequestDefaultTypeInternal() {}
  union {
    ProfileRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProfileRequestDefaultTypeInternal _ProfileRequest_default_instance_;

inline constexpr ProfileReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProfileReply::ProfileReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ProfileReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProfileReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProfileReplyDefaultTypeInternal() {}
  union {
    ProfileReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProfileReplyDefaultTypeInternal _ProfileReply_default_instance_;
}  // namespace profile
static ::_pb::Metadata file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_services_2fprofile_5fservice_2fprofile_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_services_2fprofile_5fservice_2fprofile_2eproto = nullptr;
const ::uint32_t TableStruct_services_2fprofile_5fservice_2fprofile_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::ProfileRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::ProfileRequest, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::profile::ProfileRequest, _impl_.nickname_),
    PROTOBUF_FIELD_OFFSET(::profile::ProfileRequest, _impl_.photo_),
    PROTOBUF_FIELD_OFFSET(::profile::ProfileRequest, _impl_.quote_),
    PROTOBUF_FIELD_OFFSET(::profile::ProfileRequest, _impl_.bio_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::ProfileReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::ProfileReply, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::profile::ProfileRequest)},
        {13, -1, -1, sizeof(::profile::ProfileReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::profile::_ProfileRequest_default_instance_._instance,
    &::profile::_ProfileReply_default_instance_._instance,
};
const char descriptor_table_protodef_services_2fprofile_5fservice_2fprofile_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n&services/profile_service/profile.proto"
    "\022\007profile\"Y\n\016ProfileRequest\022\n\n\002id\030\001 \001(\t\022"
    "\020\n\010nickname\030\002 \001(\t\022\r\n\005photo\030\003 \001(\t\022\r\n\005quot"
    "e\030\004 \001(\t\022\013\n\003bio\030\005 \001(\t\"\037\n\014ProfileReply\022\017\n\007"
    "message\030\001 \001(\t2\225\002\n\016ProfileService\022B\n\016Chan"
    "geNickname\022\027.profile.ProfileRequest\032\025.pr"
    "ofile.ProfileReply\"\000\022\?\n\013ChangePhoto\022\027.pr"
    "ofile.ProfileRequest\032\025.profile.ProfileRe"
    "ply\"\000\022\?\n\013ChangeQuote\022\027.profile.ProfileRe"
    "quest\032\025.profile.ProfileReply\"\000\022=\n\tChange"
    "Bio\022\027.profile.ProfileRequest\032\025.profile.P"
    "rofileReply\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto = {
    false,
    false,
    461,
    descriptor_table_protodef_services_2fprofile_5fservice_2fprofile_2eproto,
    "services/profile_service/profile.proto",
    &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_services_2fprofile_5fservice_2fprofile_2eproto::offsets,
    file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto,
    file_level_enum_descriptors_services_2fprofile_5fservice_2fprofile_2eproto,
    file_level_service_descriptors_services_2fprofile_5fservice_2fprofile_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter() {
  return &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_services_2fprofile_5fservice_2fprofile_2eproto(&descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto);
namespace profile {
// ===================================================================

class ProfileRequest::_Internal {
 public:
};

ProfileRequest::ProfileRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.ProfileRequest)
}
inline PROTOBUF_NDEBUG_INLINE ProfileRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : id_(arena, from.id_),
        nickname_(arena, from.nickname_),
        photo_(arena, from.photo_),
        quote_(arena, from.quote_),
        bio_(arena, from.bio_),
        _cached_size_{0} {}

ProfileRequest::ProfileRequest(
    ::google::protobuf::Arena* arena,
    const ProfileRequest& from)
    : ::google::protobuf::Message(arena) {
  ProfileRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:profile.ProfileRequest)
}
inline PROTOBUF_NDEBUG_INLINE ProfileRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : id_(arena),
        nickname_(arena),
        photo_(arena),
        quote_(arena),
        bio_(arena),
        _cached_size_{0} {}

inline void ProfileRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ProfileRequest::~ProfileRequest() {
  // @@protoc_insertion_point(destructor:profile.ProfileRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProfileRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.id_.Destroy();
  _impl_.nickname_.Destroy();
  _impl_.photo_.Destroy();
  _impl_.quote_.Destroy();
  _impl_.bio_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ProfileRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.ProfileRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  _impl_.nickname_.ClearToEmpty();
  _impl_.photo_.ClearToEmpty();
  _impl_.quote_.ClearToEmpty();
  _impl_.bio_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ProfileRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 54, 2> ProfileRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ProfileRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.id_)}},
    // string nickname = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.nickname_)}},
    // string photo = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.photo_)}},
    // string quote = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.quote_)}},
    // string bio = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.bio_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string nickname = 2;
    {PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.nickname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string photo = 3;
    {PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.photo_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string quote = 4;
    {PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.quote_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string bio = 5;
    {PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.bio_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\26\2\10\5\5\3\0\0"
    "profile.ProfileRequest"
    "id"
    "nickname"
    "photo"
    "quote"
    "bio"
  }},
};

::uint8_t* ProfileRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.ProfileRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    const std::string& _s = this->_internal_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "profile.ProfileRequest.id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string nickname = 2;
  if (!this->_internal_nickname().empty()) {
    const std::string& _s = this->_internal_nickname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "profile.ProfileRequest.nickname");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string photo = 3;
  if (!this->_internal_photo().empty()) {
    const std::string& _s = this->_internal_photo();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "profile.ProfileRequest.photo");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string quote = 4;
  if (!this->_internal_quote().empty()) {
    const std::string& _s = this->_internal_quote();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "profile.ProfileRequest.quote");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // string bio = 5;
  if (!this->_internal_bio().empty()) {
    const std::string& _s = this->_internal_bio();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "profile.ProfileRequest.bio");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.ProfileRequest)
  return target;
}

::size_t ProfileRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.ProfileRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_id());
  }

  // string nickname = 2;
  if (!this->_internal_nickname().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_nickname());
  }

  // string photo = 3;
  if (!this->_internal_photo().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_photo());
  }

  // string quote = 4;
  if (!this->_internal_quote().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_quote());
  }

  // string bio = 5;
  if (!this->_internal_bio().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_bio());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ProfileRequest::_class_data_ = {
    ProfileRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ProfileRequest::GetClassData() const {
  return &_class_data_;
}

void ProfileRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ProfileRequest*>(&to_msg);
  auto& from = static_cast<const ProfileRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.ProfileRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  if (!from._internal_nickname().empty()) {
    _this->_internal_set_nickname(from._internal_nickname());
  }
  if (!from._internal_photo().empty()) {
    _this->_internal_set_photo(from._internal_photo());
  }
  if (!from._internal_quote().empty()) {
    _this->_internal_set_quote(from._internal_quote());
  }
  if (!from._internal_bio().empty()) {
    _this->_internal_set_bio(from._internal_bio());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProfileRequest::CopyFrom(const ProfileRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.ProfileRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ProfileRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ProfileRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ProfileRequest::InternalSwap(ProfileRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nickname_, &other->_impl_.nickname_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.photo_, &other->_impl_.photo_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.quote_, &other->_impl_.quote_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.bio_, &other->_impl_.bio_, arena);
}

::google::protobuf::Metadata ProfileRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[0]);
}
// ===================================================================

class ProfileReply::_Internal {
 public:
};

ProfileReply::ProfileReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.ProfileReply)
}
inline PROTOBUF_NDEBUG_INLINE ProfileReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_(arena, from.message_),
        _cached_size_{0} {}

ProfileReply::ProfileReply(
    ::google::protobuf::Arena* arena,
    const ProfileReply& from)
    : ::google::protobuf::Message(arena) {
  ProfileReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:profile.ProfileReply)
}
inline PROTOBUF_NDEBUG_INLINE ProfileReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void ProfileReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ProfileReply::~ProfileReply() {
  // @@protoc_insertion_point(destructor:profile.ProfileReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProfileReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ProfileReply::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.ProfileReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ProfileReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 36, 2> ProfileReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ProfileReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ProfileReply, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(ProfileReply, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\7\0\0\0\0\0\0"
    "profile.ProfileReply"
    "message"
  }},
};

::uint8_t* ProfileReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.ProfileReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "profile.ProfileReply.message");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.ProfileReply)
  return target;
}

::size_t ProfileReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.ProfileReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ProfileReply::_class_data_ = {
    ProfileReply::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ProfileReply::GetClassData() const {
  return &_class_data_;
}

void ProfileReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ProfileReply*>(&to_msg);
  auto& from = static_cast<const ProfileReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.ProfileReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProfileReply::CopyFrom(const ProfileReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.ProfileReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ProfileReply::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ProfileReply::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ProfileReply::InternalSwap(ProfileReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata ProfileReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace profile
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
