// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/profile_service/profile.proto

#include "services/profile_service/profile.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace profile {

inline constexpr ProfileReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProfileReply::ProfileReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ProfileReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProfileReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProfileReplyDefaultTypeInternal() {}
  union {
    ProfileReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProfileReplyDefaultTypeInternal _ProfileReply_default_instance_;

inline constexpr Movie::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{0},
        rating_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Movie::Movie(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MovieDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MovieDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MovieDefaultTypeInternal() {}
  union {
    Movie _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MovieDefaultTypeInternal _Movie_default_instance_;

inline constexpr Genre::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Genre::Genre(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GenreDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenreDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenreDefaultTypeInternal() {}
  union {
    Genre _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenreDefaultTypeInternal _Genre_default_instance_;

inline constexpr Actor::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Actor::Actor(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ActorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ActorDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ActorDefaultTypeInternal() {}
  union {
    Actor _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ActorDefaultTypeInternal _Actor_default_instance_;

inline constexpr ProfileRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : movies_{},
        actors_{},
        genres_{},
        nickname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        quote_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        bio_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProfileRequest::ProfileRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ProfileRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProfileRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProfileRequestDefaultTypeInternal() {}
  union {
    ProfileRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProfileRequestDefaultTypeInternal _ProfileRequest_default_instance_;
}  // namespace profile
static ::_pb::Metadata file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[5];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_services_2fprofile_5fservice_2fprofile_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_services_2fprofile_5fservice_2fprofile_2eproto = nullptr;
const ::uint32_t TableStruct_services_2fprofile_5fservice_2fprofile_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::Movie, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::Movie, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::profile::Movie, _impl_.rating_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::Actor, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::Actor, _impl_.id_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::Genre, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::Genre, _impl_.name_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::ProfileRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::ProfileRequest, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::profile::ProfileRequest, _impl_.nickname_),
    PROTOBUF_FIELD_OFFSET(::profile::ProfileRequest, _impl_.quote_),
    PROTOBUF_FIELD_OFFSET(::profile::ProfileRequest, _impl_.bio_),
    PROTOBUF_FIELD_OFFSET(::profile::ProfileRequest, _impl_.movies_),
    PROTOBUF_FIELD_OFFSET(::profile::ProfileRequest, _impl_.actors_),
    PROTOBUF_FIELD_OFFSET(::profile::ProfileRequest, _impl_.genres_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::ProfileReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::ProfileReply, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::profile::Movie)},
        {10, -1, -1, sizeof(::profile::Actor)},
        {19, -1, -1, sizeof(::profile::Genre)},
        {28, -1, -1, sizeof(::profile::ProfileRequest)},
        {43, -1, -1, sizeof(::profile::ProfileReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::profile::_Movie_default_instance_._instance,
    &::profile::_Actor_default_instance_._instance,
    &::profile::_Genre_default_instance_._instance,
    &::profile::_ProfileRequest_default_instance_._instance,
    &::profile::_ProfileReply_default_instance_._instance,
};
const char descriptor_table_protodef_services_2fprofile_5fservice_2fprofile_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n&services/profile_service/profile.proto"
    "\022\007profile\"#\n\005Movie\022\n\n\002id\030\001 \001(\005\022\016\n\006rating"
    "\030\002 \001(\005\"\023\n\005Actor\022\n\n\002id\030\001 \001(\005\"\025\n\005Genre\022\014\n\004"
    "name\030\001 \001(\t\"\252\001\n\016ProfileRequest\022\n\n\002id\030\001 \001("
    "\005\022\020\n\010nickname\030\002 \001(\t\022\r\n\005quote\030\004 \001(\t\022\013\n\003bi"
    "o\030\005 \001(\t\022\036\n\006movies\030\006 \003(\0132\016.profile.Movie\022"
    "\036\n\006actors\030\007 \003(\0132\016.profile.Actor\022\036\n\006genre"
    "s\030\010 \003(\0132\016.profile.Genre\"\037\n\014ProfileReply\022"
    "\017\n\007message\030\001 \001(\t2\316\005\n\016ProfileService\022B\n\016C"
    "hangeNickname\022\027.profile.ProfileRequest\032\025"
    ".profile.ProfileReply\"\000\022\?\n\013ChangeQuote\022\027"
    ".profile.ProfileRequest\032\025.profile.Profil"
    "eReply\"\000\022=\n\tChangeBio\022\027.profile.ProfileR"
    "equest\032\025.profile.ProfileReply\"\000\022B\n\016AddTo"
    "Watchlist\022\027.profile.ProfileRequest\032\025.pro"
    "file.ProfileReply\"\000\022G\n\023RemoveFromWatchli"
    "st\022\027.profile.ProfileRequest\032\025.profile.Pr"
    "ofileReply\"\000\022E\n\021AddToListOfActors\022\027.prof"
    "ile.ProfileRequest\032\025.profile.ProfileRepl"
    "y\"\000\022J\n\026RemoveFromListOfActors\022\027.profile."
    "ProfileRequest\032\025.profile.ProfileReply\"\000\022"
    "E\n\021AddToListOfGenres\022\027.profile.ProfileRe"
    "quest\032\025.profile.ProfileReply\"\000\022J\n\026Remove"
    "FromListOfGenres\022\027.profile.ProfileReques"
    "t\032\025.profile.ProfileReply\"\000\022E\n\021UpdateMovi"
    "eRating\022\027.profile.ProfileRequest\032\025.profi"
    "le.ProfileReply\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto = {
    false,
    false,
    1065,
    descriptor_table_protodef_services_2fprofile_5fservice_2fprofile_2eproto,
    "services/profile_service/profile.proto",
    &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_services_2fprofile_5fservice_2fprofile_2eproto::offsets,
    file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto,
    file_level_enum_descriptors_services_2fprofile_5fservice_2fprofile_2eproto,
    file_level_service_descriptors_services_2fprofile_5fservice_2fprofile_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter() {
  return &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_services_2fprofile_5fservice_2fprofile_2eproto(&descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto);
namespace profile {
// ===================================================================

class Movie::_Internal {
 public:
};

Movie::Movie(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.Movie)
}
Movie::Movie(
    ::google::protobuf::Arena* arena, const Movie& from)
    : Movie(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Movie::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Movie::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, rating_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::rating_));
}
Movie::~Movie() {
  // @@protoc_insertion_point(destructor:profile.Movie)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Movie::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Movie::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.Movie)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.rating_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.rating_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Movie::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Movie::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Movie_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 rating = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Movie, _impl_.rating_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Movie, _impl_.rating_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Movie, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Movie, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Movie, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 rating = 2;
    {PROTOBUF_FIELD_OFFSET(Movie, _impl_.rating_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* Movie::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.Movie)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  // int32 rating = 2;
  if (this->_internal_rating() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_rating(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.Movie)
  return target;
}

::size_t Movie::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.Movie)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  // int32 rating = 2;
  if (this->_internal_rating() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_rating());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Movie::_class_data_ = {
    Movie::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Movie::GetClassData() const {
  return &_class_data_;
}

void Movie::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Movie*>(&to_msg);
  auto& from = static_cast<const Movie&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.Movie)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_rating() != 0) {
    _this->_internal_set_rating(from._internal_rating());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Movie::CopyFrom(const Movie& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.Movie)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Movie::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Movie::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Movie::InternalSwap(Movie* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Movie, _impl_.rating_)
      + sizeof(Movie::_impl_.rating_)
      - PROTOBUF_FIELD_OFFSET(Movie, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata Movie::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[0]);
}
// ===================================================================

class Actor::_Internal {
 public:
};

Actor::Actor(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.Actor)
}
Actor::Actor(
    ::google::protobuf::Arena* arena, const Actor& from)
    : Actor(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Actor::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Actor::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
Actor::~Actor() {
  // @@protoc_insertion_point(destructor:profile.Actor)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Actor::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Actor::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.Actor)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Actor::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> Actor::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Actor_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Actor, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Actor, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Actor, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* Actor::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.Actor)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.Actor)
  return target;
}

::size_t Actor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.Actor)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Actor::_class_data_ = {
    Actor::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Actor::GetClassData() const {
  return &_class_data_;
}

void Actor::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Actor*>(&to_msg);
  auto& from = static_cast<const Actor&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.Actor)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Actor::CopyFrom(const Actor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.Actor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Actor::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Actor::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Actor::InternalSwap(Actor* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata Actor::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[1]);
}
// ===================================================================

class Genre::_Internal {
 public:
};

Genre::Genre(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.Genre)
}
inline PROTOBUF_NDEBUG_INLINE Genre::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        _cached_size_{0} {}

Genre::Genre(
    ::google::protobuf::Arena* arena,
    const Genre& from)
    : ::google::protobuf::Message(arena) {
  Genre* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:profile.Genre)
}
inline PROTOBUF_NDEBUG_INLINE Genre::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void Genre::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Genre::~Genre() {
  // @@protoc_insertion_point(destructor:profile.Genre)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Genre::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Genre::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.Genre)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Genre::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 26, 2> Genre::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Genre_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Genre, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(Genre, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\15\4\0\0\0\0\0\0"
    "profile.Genre"
    "name"
  }},
};

::uint8_t* Genre::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.Genre)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "profile.Genre.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.Genre)
  return target;
}

::size_t Genre::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.Genre)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Genre::_class_data_ = {
    Genre::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Genre::GetClassData() const {
  return &_class_data_;
}

void Genre::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Genre*>(&to_msg);
  auto& from = static_cast<const Genre&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.Genre)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Genre::CopyFrom(const Genre& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.Genre)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Genre::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Genre::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Genre::InternalSwap(Genre* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata Genre::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[2]);
}
// ===================================================================

class ProfileRequest::_Internal {
 public:
};

ProfileRequest::ProfileRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.ProfileRequest)
}
inline PROTOBUF_NDEBUG_INLINE ProfileRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : movies_{visibility, arena, from.movies_},
        actors_{visibility, arena, from.actors_},
        genres_{visibility, arena, from.genres_},
        nickname_(arena, from.nickname_),
        quote_(arena, from.quote_),
        bio_(arena, from.bio_),
        _cached_size_{0} {}

ProfileRequest::ProfileRequest(
    ::google::protobuf::Arena* arena,
    const ProfileRequest& from)
    : ::google::protobuf::Message(arena) {
  ProfileRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:profile.ProfileRequest)
}
inline PROTOBUF_NDEBUG_INLINE ProfileRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : movies_{visibility, arena},
        actors_{visibility, arena},
        genres_{visibility, arena},
        nickname_(arena),
        quote_(arena),
        bio_(arena),
        _cached_size_{0} {}

inline void ProfileRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
ProfileRequest::~ProfileRequest() {
  // @@protoc_insertion_point(destructor:profile.ProfileRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProfileRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.nickname_.Destroy();
  _impl_.quote_.Destroy();
  _impl_.bio_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ProfileRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.ProfileRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.movies_.Clear();
  _impl_.actors_.Clear();
  _impl_.genres_.Clear();
  _impl_.nickname_.ClearToEmpty();
  _impl_.quote_.ClearToEmpty();
  _impl_.bio_.ClearToEmpty();
  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ProfileRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 3, 47, 2> ProfileRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967044,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ProfileRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .profile.Genre genres = 8;
    {::_pbi::TcParser::FastMtR1,
     {66, 63, 2, PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.genres_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ProfileRequest, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.id_)}},
    // string nickname = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.nickname_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // string quote = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.quote_)}},
    // string bio = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.bio_)}},
    // repeated .profile.Movie movies = 6;
    {::_pbi::TcParser::FastMtR1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.movies_)}},
    // repeated .profile.Actor actors = 7;
    {::_pbi::TcParser::FastMtR1,
     {58, 63, 1, PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.actors_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string nickname = 2;
    {PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.nickname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string quote = 4;
    {PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.quote_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string bio = 5;
    {PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.bio_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .profile.Movie movies = 6;
    {PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.movies_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .profile.Actor actors = 7;
    {PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.actors_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .profile.Genre genres = 8;
    {PROTOBUF_FIELD_OFFSET(ProfileRequest, _impl_.genres_), 0, 2,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::profile::Movie>()},
    {::_pbi::TcParser::GetTable<::profile::Actor>()},
    {::_pbi::TcParser::GetTable<::profile::Genre>()},
  }}, {{
    "\26\0\10\5\3\0\0\0"
    "profile.ProfileRequest"
    "nickname"
    "quote"
    "bio"
  }},
};

::uint8_t* ProfileRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.ProfileRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  // string nickname = 2;
  if (!this->_internal_nickname().empty()) {
    const std::string& _s = this->_internal_nickname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "profile.ProfileRequest.nickname");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string quote = 4;
  if (!this->_internal_quote().empty()) {
    const std::string& _s = this->_internal_quote();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "profile.ProfileRequest.quote");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // string bio = 5;
  if (!this->_internal_bio().empty()) {
    const std::string& _s = this->_internal_bio();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "profile.ProfileRequest.bio");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // repeated .profile.Movie movies = 6;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_movies_size()); i < n; i++) {
    const auto& repfield = this->_internal_movies().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(6, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .profile.Actor actors = 7;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_actors_size()); i < n; i++) {
    const auto& repfield = this->_internal_actors().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(7, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .profile.Genre genres = 8;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_genres_size()); i < n; i++) {
    const auto& repfield = this->_internal_genres().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(8, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.ProfileRequest)
  return target;
}

::size_t ProfileRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.ProfileRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .profile.Movie movies = 6;
  total_size += 1UL * this->_internal_movies_size();
  for (const auto& msg : this->_internal_movies()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // repeated .profile.Actor actors = 7;
  total_size += 1UL * this->_internal_actors_size();
  for (const auto& msg : this->_internal_actors()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // repeated .profile.Genre genres = 8;
  total_size += 1UL * this->_internal_genres_size();
  for (const auto& msg : this->_internal_genres()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // string nickname = 2;
  if (!this->_internal_nickname().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_nickname());
  }

  // string quote = 4;
  if (!this->_internal_quote().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_quote());
  }

  // string bio = 5;
  if (!this->_internal_bio().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_bio());
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ProfileRequest::_class_data_ = {
    ProfileRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ProfileRequest::GetClassData() const {
  return &_class_data_;
}

void ProfileRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ProfileRequest*>(&to_msg);
  auto& from = static_cast<const ProfileRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.ProfileRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_movies()->MergeFrom(
      from._internal_movies());
  _this->_internal_mutable_actors()->MergeFrom(
      from._internal_actors());
  _this->_internal_mutable_genres()->MergeFrom(
      from._internal_genres());
  if (!from._internal_nickname().empty()) {
    _this->_internal_set_nickname(from._internal_nickname());
  }
  if (!from._internal_quote().empty()) {
    _this->_internal_set_quote(from._internal_quote());
  }
  if (!from._internal_bio().empty()) {
    _this->_internal_set_bio(from._internal_bio());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProfileRequest::CopyFrom(const ProfileRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.ProfileRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ProfileRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ProfileRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ProfileRequest::InternalSwap(ProfileRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.movies_.InternalSwap(&other->_impl_.movies_);
  _impl_.actors_.InternalSwap(&other->_impl_.actors_);
  _impl_.genres_.InternalSwap(&other->_impl_.genres_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nickname_, &other->_impl_.nickname_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.quote_, &other->_impl_.quote_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.bio_, &other->_impl_.bio_, arena);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata ProfileRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[3]);
}
// ===================================================================

class ProfileReply::_Internal {
 public:
};

ProfileReply::ProfileReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.ProfileReply)
}
inline PROTOBUF_NDEBUG_INLINE ProfileReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_(arena, from.message_),
        _cached_size_{0} {}

ProfileReply::ProfileReply(
    ::google::protobuf::Arena* arena,
    const ProfileReply& from)
    : ::google::protobuf::Message(arena) {
  ProfileReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:profile.ProfileReply)
}
inline PROTOBUF_NDEBUG_INLINE ProfileReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void ProfileReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ProfileReply::~ProfileReply() {
  // @@protoc_insertion_point(destructor:profile.ProfileReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProfileReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ProfileReply::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.ProfileReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ProfileReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 36, 2> ProfileReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ProfileReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ProfileReply, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(ProfileReply, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\7\0\0\0\0\0\0"
    "profile.ProfileReply"
    "message"
  }},
};

::uint8_t* ProfileReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.ProfileReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "profile.ProfileReply.message");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.ProfileReply)
  return target;
}

::size_t ProfileReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.ProfileReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ProfileReply::_class_data_ = {
    ProfileReply::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ProfileReply::GetClassData() const {
  return &_class_data_;
}

void ProfileReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ProfileReply*>(&to_msg);
  auto& from = static_cast<const ProfileReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.ProfileReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProfileReply::CopyFrom(const ProfileReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.ProfileReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ProfileReply::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ProfileReply::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ProfileReply::InternalSwap(ProfileReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata ProfileReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[4]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace profile
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
