// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/profile_service/profile.proto

#include "services/profile_service/profile.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace profile {

inline constexpr QuoteRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : quote_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR QuoteRequest::QuoteRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct QuoteRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QuoteRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~QuoteRequestDefaultTypeInternal() {}
  union {
    QuoteRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QuoteRequestDefaultTypeInternal _QuoteRequest_default_instance_;

inline constexpr ProfileReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProfileReply::ProfileReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ProfileReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProfileReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProfileReplyDefaultTypeInternal() {}
  union {
    ProfileReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProfileReplyDefaultTypeInternal _ProfileReply_default_instance_;

inline constexpr NicknameRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : nickname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NicknameRequest::NicknameRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct NicknameRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NicknameRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NicknameRequestDefaultTypeInternal() {}
  union {
    NicknameRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NicknameRequestDefaultTypeInternal _NicknameRequest_default_instance_;

inline constexpr Movie::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{0},
        rating_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Movie::Movie(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MovieDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MovieDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MovieDefaultTypeInternal() {}
  union {
    Movie _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MovieDefaultTypeInternal _Movie_default_instance_;

inline constexpr Genre::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Genre::Genre(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GenreDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenreDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenreDefaultTypeInternal() {}
  union {
    Genre _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenreDefaultTypeInternal _Genre_default_instance_;

inline constexpr BioRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : bio_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BioRequest::BioRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct BioRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BioRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BioRequestDefaultTypeInternal() {}
  union {
    BioRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BioRequestDefaultTypeInternal _BioRequest_default_instance_;

inline constexpr Actor::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Actor::Actor(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ActorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ActorDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ActorDefaultTypeInternal() {}
  union {
    Actor _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ActorDefaultTypeInternal _Actor_default_instance_;

inline constexpr MovieRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : movies_{},
        id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MovieRequest::MovieRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MovieRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MovieRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MovieRequestDefaultTypeInternal() {}
  union {
    MovieRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MovieRequestDefaultTypeInternal _MovieRequest_default_instance_;

inline constexpr GenreRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : genres_{},
        id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GenreRequest::GenreRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GenreRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenreRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenreRequestDefaultTypeInternal() {}
  union {
    GenreRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenreRequestDefaultTypeInternal _GenreRequest_default_instance_;

inline constexpr ActorRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : actors_{},
        id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ActorRequest::ActorRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ActorRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ActorRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ActorRequestDefaultTypeInternal() {}
  union {
    ActorRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ActorRequestDefaultTypeInternal _ActorRequest_default_instance_;
}  // namespace profile
static ::_pb::Metadata file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[10];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_services_2fprofile_5fservice_2fprofile_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_services_2fprofile_5fservice_2fprofile_2eproto = nullptr;
const ::uint32_t TableStruct_services_2fprofile_5fservice_2fprofile_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::Movie, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::Movie, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::profile::Movie, _impl_.rating_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::Actor, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::Actor, _impl_.id_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::Genre, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::Genre, _impl_.name_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::NicknameRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::NicknameRequest, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::profile::NicknameRequest, _impl_.nickname_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::QuoteRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::QuoteRequest, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::profile::QuoteRequest, _impl_.quote_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::BioRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::BioRequest, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::profile::BioRequest, _impl_.bio_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::MovieRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::MovieRequest, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::profile::MovieRequest, _impl_.movies_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::ActorRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::ActorRequest, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::profile::ActorRequest, _impl_.actors_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::GenreRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::GenreRequest, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::profile::GenreRequest, _impl_.genres_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::profile::ProfileReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::profile::ProfileReply, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::profile::Movie)},
        {10, -1, -1, sizeof(::profile::Actor)},
        {19, -1, -1, sizeof(::profile::Genre)},
        {28, -1, -1, sizeof(::profile::NicknameRequest)},
        {38, -1, -1, sizeof(::profile::QuoteRequest)},
        {48, -1, -1, sizeof(::profile::BioRequest)},
        {58, -1, -1, sizeof(::profile::MovieRequest)},
        {68, -1, -1, sizeof(::profile::ActorRequest)},
        {78, -1, -1, sizeof(::profile::GenreRequest)},
        {88, -1, -1, sizeof(::profile::ProfileReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::profile::_Movie_default_instance_._instance,
    &::profile::_Actor_default_instance_._instance,
    &::profile::_Genre_default_instance_._instance,
    &::profile::_NicknameRequest_default_instance_._instance,
    &::profile::_QuoteRequest_default_instance_._instance,
    &::profile::_BioRequest_default_instance_._instance,
    &::profile::_MovieRequest_default_instance_._instance,
    &::profile::_ActorRequest_default_instance_._instance,
    &::profile::_GenreRequest_default_instance_._instance,
    &::profile::_ProfileReply_default_instance_._instance,
};
const char descriptor_table_protodef_services_2fprofile_5fservice_2fprofile_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n&services/profile_service/profile.proto"
    "\022\007profile\"#\n\005Movie\022\n\n\002id\030\001 \001(\005\022\016\n\006rating"
    "\030\002 \001(\005\"\023\n\005Actor\022\n\n\002id\030\001 \001(\005\"\025\n\005Genre\022\014\n\004"
    "name\030\001 \001(\t\"/\n\017NicknameRequest\022\n\n\002id\030\001 \001("
    "\005\022\020\n\010nickname\030\002 \001(\t\")\n\014QuoteRequest\022\n\n\002i"
    "d\030\001 \001(\005\022\r\n\005quote\030\002 \001(\t\"%\n\nBioRequest\022\n\n\002"
    "id\030\001 \001(\005\022\013\n\003bio\030\002 \001(\t\":\n\014MovieRequest\022\n\n"
    "\002id\030\001 \001(\005\022\036\n\006movies\030\002 \003(\0132\016.profile.Movi"
    "e\":\n\014ActorRequest\022\n\n\002id\030\001 \001(\005\022\036\n\006actors\030"
    "\002 \003(\0132\016.profile.Actor\":\n\014GenreRequest\022\n\n"
    "\002id\030\001 \001(\005\022\036\n\006genres\030\002 \003(\0132\016.profile.Genr"
    "e\"\037\n\014ProfileReply\022\017\n\007message\030\001 \001(\t2\366\004\n\016P"
    "rofileService\022C\n\016ChangeNickname\022\030.profil"
    "e.NicknameRequest\032\025.profile.ProfileReply"
    "\"\000\022=\n\013ChangeQuote\022\025.profile.QuoteRequest"
    "\032\025.profile.ProfileReply\"\000\0229\n\tChangeBio\022\023"
    ".profile.BioRequest\032\025.profile.ProfileRep"
    "ly\"\000\022@\n\016AddToWatchlist\022\025.profile.MovieRe"
    "quest\032\025.profile.ProfileReply\"\000\022E\n\023Remove"
    "FromWatchlist\022\025.profile.MovieRequest\032\025.p"
    "rofile.ProfileReply\"\000\022C\n\021AddToListOfActo"
    "rs\022\025.profile.ActorRequest\032\025.profile.Prof"
    "ileReply\"\000\022H\n\026RemoveFromListOfActors\022\025.p"
    "rofile.ActorRequest\032\025.profile.ProfileRep"
    "ly\"\000\022C\n\021AddToListOfGenres\022\025.profile.Genr"
    "eRequest\032\025.profile.ProfileReply\"\000\022H\n\026Rem"
    "oveFromListOfGenres\022\025.profile.GenreReque"
    "st\032\025.profile.ProfileReply\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto = {
    false,
    false,
    1115,
    descriptor_table_protodef_services_2fprofile_5fservice_2fprofile_2eproto,
    "services/profile_service/profile.proto",
    &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
    nullptr,
    0,
    10,
    schemas,
    file_default_instances,
    TableStruct_services_2fprofile_5fservice_2fprofile_2eproto::offsets,
    file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto,
    file_level_enum_descriptors_services_2fprofile_5fservice_2fprofile_2eproto,
    file_level_service_descriptors_services_2fprofile_5fservice_2fprofile_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter() {
  return &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_services_2fprofile_5fservice_2fprofile_2eproto(&descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto);
namespace profile {
// ===================================================================

class Movie::_Internal {
 public:
};

Movie::Movie(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.Movie)
}
Movie::Movie(
    ::google::protobuf::Arena* arena, const Movie& from)
    : Movie(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Movie::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Movie::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, rating_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::rating_));
}
Movie::~Movie() {
  // @@protoc_insertion_point(destructor:profile.Movie)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Movie::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Movie::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.Movie)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.rating_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.rating_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Movie::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Movie::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Movie_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 rating = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Movie, _impl_.rating_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Movie, _impl_.rating_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Movie, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Movie, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Movie, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 rating = 2;
    {PROTOBUF_FIELD_OFFSET(Movie, _impl_.rating_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* Movie::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.Movie)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  // int32 rating = 2;
  if (this->_internal_rating() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_rating(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.Movie)
  return target;
}

::size_t Movie::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.Movie)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  // int32 rating = 2;
  if (this->_internal_rating() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_rating());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Movie::_class_data_ = {
    Movie::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Movie::GetClassData() const {
  return &_class_data_;
}

void Movie::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Movie*>(&to_msg);
  auto& from = static_cast<const Movie&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.Movie)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_rating() != 0) {
    _this->_internal_set_rating(from._internal_rating());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Movie::CopyFrom(const Movie& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.Movie)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Movie::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Movie::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Movie::InternalSwap(Movie* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Movie, _impl_.rating_)
      + sizeof(Movie::_impl_.rating_)
      - PROTOBUF_FIELD_OFFSET(Movie, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata Movie::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[0]);
}
// ===================================================================

class Actor::_Internal {
 public:
};

Actor::Actor(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.Actor)
}
Actor::Actor(
    ::google::protobuf::Arena* arena, const Actor& from)
    : Actor(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Actor::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Actor::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
Actor::~Actor() {
  // @@protoc_insertion_point(destructor:profile.Actor)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Actor::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Actor::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.Actor)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Actor::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> Actor::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Actor_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Actor, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Actor, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Actor, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* Actor::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.Actor)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.Actor)
  return target;
}

::size_t Actor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.Actor)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Actor::_class_data_ = {
    Actor::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Actor::GetClassData() const {
  return &_class_data_;
}

void Actor::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Actor*>(&to_msg);
  auto& from = static_cast<const Actor&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.Actor)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Actor::CopyFrom(const Actor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.Actor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Actor::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Actor::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Actor::InternalSwap(Actor* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata Actor::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[1]);
}
// ===================================================================

class Genre::_Internal {
 public:
};

Genre::Genre(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.Genre)
}
inline PROTOBUF_NDEBUG_INLINE Genre::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        _cached_size_{0} {}

Genre::Genre(
    ::google::protobuf::Arena* arena,
    const Genre& from)
    : ::google::protobuf::Message(arena) {
  Genre* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:profile.Genre)
}
inline PROTOBUF_NDEBUG_INLINE Genre::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void Genre::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Genre::~Genre() {
  // @@protoc_insertion_point(destructor:profile.Genre)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Genre::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Genre::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.Genre)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Genre::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 26, 2> Genre::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Genre_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Genre, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(Genre, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\15\4\0\0\0\0\0\0"
    "profile.Genre"
    "name"
  }},
};

::uint8_t* Genre::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.Genre)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "profile.Genre.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.Genre)
  return target;
}

::size_t Genre::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.Genre)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Genre::_class_data_ = {
    Genre::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Genre::GetClassData() const {
  return &_class_data_;
}

void Genre::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Genre*>(&to_msg);
  auto& from = static_cast<const Genre&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.Genre)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Genre::CopyFrom(const Genre& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.Genre)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Genre::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Genre::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Genre::InternalSwap(Genre* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata Genre::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[2]);
}
// ===================================================================

class NicknameRequest::_Internal {
 public:
};

NicknameRequest::NicknameRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.NicknameRequest)
}
inline PROTOBUF_NDEBUG_INLINE NicknameRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : nickname_(arena, from.nickname_),
        _cached_size_{0} {}

NicknameRequest::NicknameRequest(
    ::google::protobuf::Arena* arena,
    const NicknameRequest& from)
    : ::google::protobuf::Message(arena) {
  NicknameRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:profile.NicknameRequest)
}
inline PROTOBUF_NDEBUG_INLINE NicknameRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : nickname_(arena),
        _cached_size_{0} {}

inline void NicknameRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
NicknameRequest::~NicknameRequest() {
  // @@protoc_insertion_point(destructor:profile.NicknameRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void NicknameRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.nickname_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void NicknameRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.NicknameRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.nickname_.ClearToEmpty();
  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* NicknameRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 40, 2> NicknameRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_NicknameRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string nickname = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(NicknameRequest, _impl_.nickname_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NicknameRequest, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(NicknameRequest, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(NicknameRequest, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string nickname = 2;
    {PROTOBUF_FIELD_OFFSET(NicknameRequest, _impl_.nickname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\0\10\0\0\0\0\0"
    "profile.NicknameRequest"
    "nickname"
  }},
};

::uint8_t* NicknameRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.NicknameRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  // string nickname = 2;
  if (!this->_internal_nickname().empty()) {
    const std::string& _s = this->_internal_nickname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "profile.NicknameRequest.nickname");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.NicknameRequest)
  return target;
}

::size_t NicknameRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.NicknameRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string nickname = 2;
  if (!this->_internal_nickname().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_nickname());
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData NicknameRequest::_class_data_ = {
    NicknameRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* NicknameRequest::GetClassData() const {
  return &_class_data_;
}

void NicknameRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<NicknameRequest*>(&to_msg);
  auto& from = static_cast<const NicknameRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.NicknameRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_nickname().empty()) {
    _this->_internal_set_nickname(from._internal_nickname());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NicknameRequest::CopyFrom(const NicknameRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.NicknameRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool NicknameRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* NicknameRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void NicknameRequest::InternalSwap(NicknameRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nickname_, &other->_impl_.nickname_, arena);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata NicknameRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[3]);
}
// ===================================================================

class QuoteRequest::_Internal {
 public:
};

QuoteRequest::QuoteRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.QuoteRequest)
}
inline PROTOBUF_NDEBUG_INLINE QuoteRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : quote_(arena, from.quote_),
        _cached_size_{0} {}

QuoteRequest::QuoteRequest(
    ::google::protobuf::Arena* arena,
    const QuoteRequest& from)
    : ::google::protobuf::Message(arena) {
  QuoteRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:profile.QuoteRequest)
}
inline PROTOBUF_NDEBUG_INLINE QuoteRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : quote_(arena),
        _cached_size_{0} {}

inline void QuoteRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
QuoteRequest::~QuoteRequest() {
  // @@protoc_insertion_point(destructor:profile.QuoteRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void QuoteRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.quote_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void QuoteRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.QuoteRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.quote_.ClearToEmpty();
  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* QuoteRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 34, 2> QuoteRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_QuoteRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string quote = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(QuoteRequest, _impl_.quote_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(QuoteRequest, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(QuoteRequest, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(QuoteRequest, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string quote = 2;
    {PROTOBUF_FIELD_OFFSET(QuoteRequest, _impl_.quote_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\0\5\0\0\0\0\0"
    "profile.QuoteRequest"
    "quote"
  }},
};

::uint8_t* QuoteRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.QuoteRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  // string quote = 2;
  if (!this->_internal_quote().empty()) {
    const std::string& _s = this->_internal_quote();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "profile.QuoteRequest.quote");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.QuoteRequest)
  return target;
}

::size_t QuoteRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.QuoteRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string quote = 2;
  if (!this->_internal_quote().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_quote());
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData QuoteRequest::_class_data_ = {
    QuoteRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* QuoteRequest::GetClassData() const {
  return &_class_data_;
}

void QuoteRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<QuoteRequest*>(&to_msg);
  auto& from = static_cast<const QuoteRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.QuoteRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_quote().empty()) {
    _this->_internal_set_quote(from._internal_quote());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void QuoteRequest::CopyFrom(const QuoteRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.QuoteRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool QuoteRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* QuoteRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void QuoteRequest::InternalSwap(QuoteRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.quote_, &other->_impl_.quote_, arena);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata QuoteRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[4]);
}
// ===================================================================

class BioRequest::_Internal {
 public:
};

BioRequest::BioRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.BioRequest)
}
inline PROTOBUF_NDEBUG_INLINE BioRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : bio_(arena, from.bio_),
        _cached_size_{0} {}

BioRequest::BioRequest(
    ::google::protobuf::Arena* arena,
    const BioRequest& from)
    : ::google::protobuf::Message(arena) {
  BioRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:profile.BioRequest)
}
inline PROTOBUF_NDEBUG_INLINE BioRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : bio_(arena),
        _cached_size_{0} {}

inline void BioRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
BioRequest::~BioRequest() {
  // @@protoc_insertion_point(destructor:profile.BioRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void BioRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.bio_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void BioRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.BioRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.bio_.ClearToEmpty();
  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* BioRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 30, 2> BioRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_BioRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string bio = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(BioRequest, _impl_.bio_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BioRequest, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(BioRequest, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(BioRequest, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string bio = 2;
    {PROTOBUF_FIELD_OFFSET(BioRequest, _impl_.bio_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\0\3\0\0\0\0\0"
    "profile.BioRequest"
    "bio"
  }},
};

::uint8_t* BioRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.BioRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  // string bio = 2;
  if (!this->_internal_bio().empty()) {
    const std::string& _s = this->_internal_bio();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "profile.BioRequest.bio");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.BioRequest)
  return target;
}

::size_t BioRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.BioRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string bio = 2;
  if (!this->_internal_bio().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_bio());
  }

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData BioRequest::_class_data_ = {
    BioRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* BioRequest::GetClassData() const {
  return &_class_data_;
}

void BioRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<BioRequest*>(&to_msg);
  auto& from = static_cast<const BioRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.BioRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_bio().empty()) {
    _this->_internal_set_bio(from._internal_bio());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BioRequest::CopyFrom(const BioRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.BioRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool BioRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* BioRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void BioRequest::InternalSwap(BioRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.bio_, &other->_impl_.bio_, arena);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata BioRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[5]);
}
// ===================================================================

class MovieRequest::_Internal {
 public:
};

MovieRequest::MovieRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.MovieRequest)
}
inline PROTOBUF_NDEBUG_INLINE MovieRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : movies_{visibility, arena, from.movies_},
        _cached_size_{0} {}

MovieRequest::MovieRequest(
    ::google::protobuf::Arena* arena,
    const MovieRequest& from)
    : ::google::protobuf::Message(arena) {
  MovieRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:profile.MovieRequest)
}
inline PROTOBUF_NDEBUG_INLINE MovieRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : movies_{visibility, arena},
        _cached_size_{0} {}

inline void MovieRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
MovieRequest::~MovieRequest() {
  // @@protoc_insertion_point(destructor:profile.MovieRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MovieRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void MovieRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.MovieRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.movies_.Clear();
  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MovieRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> MovieRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_MovieRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .profile.Movie movies = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(MovieRequest, _impl_.movies_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MovieRequest, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MovieRequest, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(MovieRequest, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated .profile.Movie movies = 2;
    {PROTOBUF_FIELD_OFFSET(MovieRequest, _impl_.movies_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::profile::Movie>()},
  }}, {{
  }},
};

::uint8_t* MovieRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.MovieRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  // repeated .profile.Movie movies = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_movies_size()); i < n; i++) {
    const auto& repfield = this->_internal_movies().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.MovieRequest)
  return target;
}

::size_t MovieRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.MovieRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .profile.Movie movies = 2;
  total_size += 1UL * this->_internal_movies_size();
  for (const auto& msg : this->_internal_movies()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData MovieRequest::_class_data_ = {
    MovieRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* MovieRequest::GetClassData() const {
  return &_class_data_;
}

void MovieRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<MovieRequest*>(&to_msg);
  auto& from = static_cast<const MovieRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.MovieRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_movies()->MergeFrom(
      from._internal_movies());
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MovieRequest::CopyFrom(const MovieRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.MovieRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MovieRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* MovieRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void MovieRequest::InternalSwap(MovieRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.movies_.InternalSwap(&other->_impl_.movies_);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata MovieRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[6]);
}
// ===================================================================

class ActorRequest::_Internal {
 public:
};

ActorRequest::ActorRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.ActorRequest)
}
inline PROTOBUF_NDEBUG_INLINE ActorRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : actors_{visibility, arena, from.actors_},
        _cached_size_{0} {}

ActorRequest::ActorRequest(
    ::google::protobuf::Arena* arena,
    const ActorRequest& from)
    : ::google::protobuf::Message(arena) {
  ActorRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:profile.ActorRequest)
}
inline PROTOBUF_NDEBUG_INLINE ActorRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : actors_{visibility, arena},
        _cached_size_{0} {}

inline void ActorRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
ActorRequest::~ActorRequest() {
  // @@protoc_insertion_point(destructor:profile.ActorRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ActorRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ActorRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.ActorRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.actors_.Clear();
  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ActorRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> ActorRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ActorRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .profile.Actor actors = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ActorRequest, _impl_.actors_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ActorRequest, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ActorRequest, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(ActorRequest, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated .profile.Actor actors = 2;
    {PROTOBUF_FIELD_OFFSET(ActorRequest, _impl_.actors_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::profile::Actor>()},
  }}, {{
  }},
};

::uint8_t* ActorRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.ActorRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  // repeated .profile.Actor actors = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_actors_size()); i < n; i++) {
    const auto& repfield = this->_internal_actors().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.ActorRequest)
  return target;
}

::size_t ActorRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.ActorRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .profile.Actor actors = 2;
  total_size += 1UL * this->_internal_actors_size();
  for (const auto& msg : this->_internal_actors()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ActorRequest::_class_data_ = {
    ActorRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ActorRequest::GetClassData() const {
  return &_class_data_;
}

void ActorRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ActorRequest*>(&to_msg);
  auto& from = static_cast<const ActorRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.ActorRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_actors()->MergeFrom(
      from._internal_actors());
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ActorRequest::CopyFrom(const ActorRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.ActorRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ActorRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ActorRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ActorRequest::InternalSwap(ActorRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.actors_.InternalSwap(&other->_impl_.actors_);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata ActorRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[7]);
}
// ===================================================================

class GenreRequest::_Internal {
 public:
};

GenreRequest::GenreRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.GenreRequest)
}
inline PROTOBUF_NDEBUG_INLINE GenreRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : genres_{visibility, arena, from.genres_},
        _cached_size_{0} {}

GenreRequest::GenreRequest(
    ::google::protobuf::Arena* arena,
    const GenreRequest& from)
    : ::google::protobuf::Message(arena) {
  GenreRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:profile.GenreRequest)
}
inline PROTOBUF_NDEBUG_INLINE GenreRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : genres_{visibility, arena},
        _cached_size_{0} {}

inline void GenreRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
GenreRequest::~GenreRequest() {
  // @@protoc_insertion_point(destructor:profile.GenreRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GenreRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void GenreRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.GenreRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.genres_.Clear();
  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GenreRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> GenreRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_GenreRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .profile.Genre genres = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(GenreRequest, _impl_.genres_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GenreRequest, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GenreRequest, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(GenreRequest, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated .profile.Genre genres = 2;
    {PROTOBUF_FIELD_OFFSET(GenreRequest, _impl_.genres_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::profile::Genre>()},
  }}, {{
  }},
};

::uint8_t* GenreRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.GenreRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  // repeated .profile.Genre genres = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_genres_size()); i < n; i++) {
    const auto& repfield = this->_internal_genres().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.GenreRequest)
  return target;
}

::size_t GenreRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.GenreRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .profile.Genre genres = 2;
  total_size += 1UL * this->_internal_genres_size();
  for (const auto& msg : this->_internal_genres()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GenreRequest::_class_data_ = {
    GenreRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GenreRequest::GetClassData() const {
  return &_class_data_;
}

void GenreRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GenreRequest*>(&to_msg);
  auto& from = static_cast<const GenreRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.GenreRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_genres()->MergeFrom(
      from._internal_genres());
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GenreRequest::CopyFrom(const GenreRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.GenreRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GenreRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GenreRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GenreRequest::InternalSwap(GenreRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.genres_.InternalSwap(&other->_impl_.genres_);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata GenreRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[8]);
}
// ===================================================================

class ProfileReply::_Internal {
 public:
};

ProfileReply::ProfileReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:profile.ProfileReply)
}
inline PROTOBUF_NDEBUG_INLINE ProfileReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_(arena, from.message_),
        _cached_size_{0} {}

ProfileReply::ProfileReply(
    ::google::protobuf::Arena* arena,
    const ProfileReply& from)
    : ::google::protobuf::Message(arena) {
  ProfileReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:profile.ProfileReply)
}
inline PROTOBUF_NDEBUG_INLINE ProfileReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void ProfileReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ProfileReply::~ProfileReply() {
  // @@protoc_insertion_point(destructor:profile.ProfileReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ProfileReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ProfileReply::Clear() {
// @@protoc_insertion_point(message_clear_start:profile.ProfileReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ProfileReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 36, 2> ProfileReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ProfileReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ProfileReply, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(ProfileReply, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\7\0\0\0\0\0\0"
    "profile.ProfileReply"
    "message"
  }},
};

::uint8_t* ProfileReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:profile.ProfileReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "profile.ProfileReply.message");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:profile.ProfileReply)
  return target;
}

::size_t ProfileReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:profile.ProfileReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ProfileReply::_class_data_ = {
    ProfileReply::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ProfileReply::GetClassData() const {
  return &_class_data_;
}

void ProfileReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ProfileReply*>(&to_msg);
  auto& from = static_cast<const ProfileReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:profile.ProfileReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProfileReply::CopyFrom(const ProfileReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:profile.ProfileReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ProfileReply::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ProfileReply::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ProfileReply::InternalSwap(ProfileReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata ProfileReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_getter, &descriptor_table_services_2fprofile_5fservice_2fprofile_2eproto_once,
      file_level_metadata_services_2fprofile_5fservice_2fprofile_2eproto[9]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace profile
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
